export const majors = [
  {
    value: "Advertising and/or Marketing",
    text: "Advertising and/or Marketing",
  },
  {
    value: "Applied Mathematics and Social Sciences",
    text: "Applied Mathematics and Social Sciences",
  },
  { value: "Architecture", text: "Architecture" },
  { value: "Arts", text: "Arts" },
  { value: "Audit", text: "Audit" },
  { value: "Banking and Finance", text: "Banking and Finance" },
  { value: "Business Administration", text: "Business Administration" },
  { value: "Business Computing", text: "Business Computing" },
  { value: "Business Management", text: "Business Management" },
  { value: "Civil Engineering", text: "Civil Engineering" },
  { value: "Communication", text: "Communication" },
  {
    value: "Computer and Communication Engineering",
    text: "Computer and Communication Engineering",
  },
  { value: "Computer Science", text: "Computer Science" },
  { value: "Economics", text: "Economics" },
  { value: "Education", text: "Education" },
  { value: "Electerical Engineering", text: "Electerical Engineering" },
  { value: "Entrepreneurship", text: "Entrepreneurship" },
  { value: "Financial Assets", text: "Financial Assets" },
  { value: "Financial Engineering", text: "Financial Engineering" },
  { value: "Graphic Design", text: "Graphic Design" },
  { value: "Hospitality Management", text: "Hospitality Management" },
  { value: "Human Resources", text: "Human Resources" },
  { value: "Industrial Electronics", text: "Industrial Electronics" },
  { value: "Information Security", text: "Information Security" },
  { value: "Information Technology", text: "Information Technology" },
  { value: "Insurance", text: "Insurance" },
  { value: "Interior Design", text: "Interior Design" },
  { value: "Journalism", text: "Journalism" },
  { value: "Law", text: "Law" },
  { value: "Law and Political Science", text: "Law and Political Science" },
  { value: "Literature", text: "Literature" },
  { value: "Logistics", text: "Logistics" },
  {
    value: "Management Information Systems",
    text: "Management Information Systems",
  },
  { value: "Marketing", text: "Marketing" },
  { value: "Management", text: "Management" },
  { value: "Mathematics", text: "Mathematics" },
  { value: "Mechanical Engineering", text: "Mechanical Engineering" },
  {
    value: "Political Science and Administration",
    text: "Political Science and Administration",
  },
  { value: "Psychology", text: "Psychology" },
  {
    value: "Public Relations and Communication",
    text: "Public Relations and Communication",
  },
  { value: "Real Estate", text: "Real Estate" },
  { value: "Risk Management", text: "Risk Management" },
  { value: "Statistics", text: "Statistics" },
  { value: "Strategic Management", text: "Strategic Management" },
  { value: "Systems and Networking", text: "Systems and Networking" },
  { value: "Telecommunication", text: "Telecommunication" },
  {
    value: "Telecommunication and Network",
    text: "Telecommunication and Network",
  },
  { value: "Tourism", text: "Tourism" },
  { value: "Translation", text: "Translation" },
  { value: "Other", text: "Other" },
];
